spring:
  data:
    mongodb:
      uri: "mongodb+srv://vermapv749_db_user:h9rR4t5463yG7rxW@quicktext-cluster.8rm5ekc.mongodb.net/?appName=quicktext-cluster"
      database: "quicktextdb"

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

jwt:
  secretKey: "ads9f6ask3h4k1hf86asdfiahkjh34a789s6df89ayshkjh3jkh786ads78ay"

profileUrl: "https://res.cloudinary.com/dacxt4qjt/image/upload/profile_kk4erj.png"

cloudinary:
  cloud-name: "dacxt4qjt"
  api-key: "522395392912923"
  api-secret: "0sRJKH16mAbdGnjyb8CuFVuuqNg"

frontend-url: "http://localhost:5173"