spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27017/quicktext"
      database: quicktextdb


logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

jwt:
  secretKey: ${SECRET_KEY}

profileUrl: "https://res.cloudinary.com/dacxt4qjt/image/upload/profile_kk4erj.png"

cloudinary:
  cloud-name: "dacxt4qjt"
  api-key: ${API_KEY}
  api-secret: ${API_SECRET}

frontend-url: ${FRONTEND_URL}